#!/bin/bash


# Extract fields from JSON
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
height_m=$(jq -r '.height' data.json | awk '{printf "%.1f", $1/10}')
weight_kg=$(jq -r '.weight' data.json | awk '{printf "%.1f", $1/10}')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

# Print human-readable output
echo "$name is of type $type, weighs ${weight_kg}kg, and is ${height_m}m tall."
